title: "Marwan Benyoussef"
author: "Marwan Benyoussef"
description: "Freie Universitaet Berlin."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "research.md", title: "Research"}
  - {file: "seminars.html", title: "Seminars"}
  - {file: "teaching.md", title: "Teaching"}
  - {file: "README.md", title: "Math journey"}  
  - {file: "contact.md", title: "Contact"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:marwan.benyoussef@gmail.com"}
  - {title: Github, icon: github, url: "https://marwanus.github.io/mben.github.io/"}
  - {title: LinkedIn, icon: linkedin, url: "linkedin.com/in/marwan-benyoussef-94241542"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
